# Usage
#   Start:          docker-compose -f docker-compose.frontend.yml up -d

name: weather-app
version: "3.8"

services:
  frontend:
    image: image-env
    networks:
      - dev-server-bootstrap_traefik-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 10M
        reservations:
          memory: 10M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`ec2-54-189-157-96.us-west-2.compute.amazonaws.com`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"
        - "traefik.http.routers.frontend.service=frontend"
        - "traefik.docker.network=dev-server-bootstrap_traefik-net"

networks:
  dev-server-bootstrap_traefik-net:
    external: true