spring:
  cloud:
    openfeign:
      client:
        config:
          weather:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_WEATHER_URL}
          geocode:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_GEOCODE_URL}
weather:
  apikey: ${WEATHER_APIKEY}

server:
  port: ${SERVER_PORT}